apiVersion: batch/v1
kind: Job
metadata:
  name: tvk-license-ovhcloud
  namespace: tvk
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
      - name: generate-tvk-license
        image: eu.gcr.io/amazing-chalice-243510/ovh_license:latest
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        imagePullPolicy: Always
      restartPolicy: Never
      schedulerName: default-scheduler
      serviceAccount: "k8s-triliovault"
      serviceAccountName: "k8s-triliovault"
      terminationGracePeriodSeconds: 30

